import { useLocalSearchParams, useRouter } from 'expo-router'; import { useEffect, useMemo, useState } from 'react'; import { Alert, StyleSheet, Text } from 'react-native';
import { Botao } from '../src/components/Botao'; import { Campo } from '../src/components/Campo'; import { EstadoTela } from '../src/components/EstadoTela'; import { Seletor } from '../src/components/Seletor'; import { Tela } from '../src/components/Tela'; import { useServicoGastos } from '../src/data/sqlite/expenseServices'; import { mensagemErro } from '../src/domain/errors'; import type { CategoriaGasto, SubcategoriaGasto } from '../src/features/expenses/types'; import { dataIsoParaPtBr, dataPtBrParaIso, reaisParaCentavos } from '../src/features/expenses/validation'; import { data } from '../src/lib/formato'; import { cores, espaco, tipografia } from '../src/theme/tokens';
export default function FormularioGasto() {
  const router = useRouter(); const params = useLocalSearchParams<{ id?: string }>(); const id = params.id ? Number(params.id) : undefined; const servico = useServicoGastos();
  const [categorias, setCategorias] = useState<CategoriaGasto[]>([]); const [subcategorias, setSubcategorias] = useState<SubcategoriaGasto[]>([]); const [descricao, setDescricao] = useState(''); const [categoriaId, setCategoriaId] = useState<number | null>(null); const [subcategoriaId, setSubcategoriaId] = useState<number | null>(null); const [valor, setValor] = useState(''); const [dataGasto, setDataGasto] = useState(data(new Date())); const [carregando, setCarregando] = useState(true); const [salvando, setSalvando] = useState(false);
  useEffect(() => { void (async () => { try { const [cats, subs] = await Promise.all([servico.listarCategorias(), servico.listarSubcategorias()]); setCategorias(cats); setSubcategorias(subs); if (id) { const gasto = await servico.obterGasto(id); if (!gasto) throw new Error('Gasto não encontrado.'); setDescricao(gasto.descricao); setCategoriaId(gasto.categoriaId); setSubcategoriaId(gasto.subcategoriaId); setValor((gasto.valorCentavos / 100).toFixed(2).replace('.', ',')); setDataGasto(dataIsoParaPtBr(gasto.data)); } else if (cats.length === 1) setCategoriaId(cats[0].id); } catch (causa) { Alert.alert('Não foi possível carregar', mensagemErro(causa)); } finally { setCarregando(false); } })(); }, [id, servico]);
  const subsDisponiveis = useMemo(() => subcategorias.filter((sub) => sub.categoriaId === categoriaId), [categoriaId, subcategorias]); const selecionarCategoria = (nova: number) => { setCategoriaId(nova); setSubcategoriaId(null); };
  const salvar = async () => { setSalvando(true); try { await servico.salvarGasto({ descricao, categoriaId: categoriaId ?? 0, subcategoriaId, valorCentavos: reaisParaCentavos(valor), data: dataPtBrParaIso(dataGasto) }, id); router.back(); } catch (causa) { Alert.alert('Revise os dados', mensagemErro(causa)); } finally { setSalvando(false); } };
  if (carregando) return <Tela><EstadoTela mensagem="Carregando formulário…" carregando /></Tela>;
  return <Tela><Text style={estilos.titulo}>{id ? 'Editar gasto' : 'Novo gasto'}</Text><Campo rotulo="Descrição" value={descricao} onChangeText={setDescricao} placeholder="Ex.: Compra de sal mineral" /><Seletor rotulo="Categoria" valor={categoriaId} opcoes={categorias.map((cat) => ({ valor: cat.id, rotulo: cat.nome }))} aoSelecionar={selecionarCategoria} />{subsDisponiveis.length > 0 ? <Seletor rotulo="Subcategoria (opcional)" valor={subcategoriaId} opcoes={subsDisponiveis.map((sub) => ({ valor: sub.id, rotulo: sub.nome }))} aoSelecionar={setSubcategoriaId} /> : null}{subcategoriaId ? <Botao titulo="Remover subcategoria" variante="secundario" onPress={() => setSubcategoriaId(null)} /> : null}<Campo rotulo="Valor (R$)" value={valor} onChangeText={setValor} keyboardType="decimal-pad" placeholder="0,00" /><Campo rotulo="Data" ajuda="Formato DD/MM/AAAA" value={dataGasto} onChangeText={setDataGasto} keyboardType="number-pad" placeholder="DD/MM/AAAA" maxLength={10} /><Botao titulo={id ? 'Salvar alterações' : 'Registrar gasto'} carregando={salvando} onPress={salvar} /><Botao titulo="Gerenciar categorias" variante="secundario" onPress={() => router.push('/categorias-gasto')} /></Tela>;
}
const estilos = StyleSheet.create({ titulo: { ...tipografia.headingSm, color: cores.tinta, marginBottom: espaco.sm } });
