import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Botao } from '../src/components/Botao'; import { Campo } from '../src/components/Campo'; import { Cartao } from '../src/components/Cartao'; import { EstadoTela } from '../src/components/EstadoTela'; import { Tela } from '../src/components/Tela';
import { useServicoPastos } from '../src/data/sqlite/pastureServices'; import { mensagemErro } from '../src/domain/errors'; import type { TipoCapim } from '../src/features/pastures/types'; import { cores, espaco, tipografia } from '../src/theme/tokens';
const converter = (valor: string) => Number(valor.trim().replace(',', '.'));
export default function TelaTiposCapim() {
  const servico = useServicoPastos(); const [tipos, setTipos] = useState<TipoCapim[]>([]); const [editando, setEditando] = useState<number>();
  const [nome, setNome] = useState(''); const [minima, setMinima] = useState(''); const [maxima, setMaxima] = useState(''); const [carregando, setCarregando] = useState(true); const [salvando, setSalvando] = useState(false);
  const carregar = useCallback(async () => { setCarregando(true); try { setTipos(await servico.listarTipos()); } catch (causa) { Alert.alert('Não foi possível carregar', mensagemErro(causa)); } finally { setCarregando(false); } }, [servico]);
  useFocusEffect(useCallback(() => { void carregar(); }, [carregar]));
  const limpar = () => { setEditando(undefined); setNome(''); setMinima(''); setMaxima(''); };
  const editar = (tipo: TipoCapim) => { setEditando(tipo.id); setNome(tipo.nome); setMinima(String(tipo.alturaMinimaCm).replace('.', ',')); setMaxima(String(tipo.alturaMaximaCm).replace('.', ',')); };
  const salvar = async () => { setSalvando(true); try { await servico.salvarTipo({ nome, alturaMinimaCm: converter(minima), alturaMaximaCm: converter(maxima) }, editando); limpar(); await carregar(); } catch (causa) { Alert.alert('Revise os dados', mensagemErro(causa)); } finally { setSalvando(false); } };
  const excluir = (tipo: TipoCapim) => Alert.alert('Excluir tipo de capim?', `“${tipo.nome}” só pode ser excluído se não estiver associado a nenhum pasto.`, [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { try { await servico.excluirTipo(tipo.id); await carregar(); } catch (causa) { Alert.alert('Não foi possível excluir', mensagemErro(causa)); } } }]);
  return <Tela><Cartao style={estilos.formulario}><Text style={estilos.titulo}>{editando ? 'Editar tipo de capim' : 'Novo tipo de capim'}</Text><Campo rotulo="Nome" value={nome} onChangeText={setNome} placeholder="Ex.: Braquiária" /><Campo rotulo="Altura mínima adequada (cm)" value={minima} onChangeText={setMinima} keyboardType="decimal-pad" /><Campo rotulo="Altura máxima adequada (cm)" value={maxima} onChangeText={setMaxima} keyboardType="decimal-pad" /><Botao titulo={editando ? 'Salvar alterações' : 'Cadastrar tipo'} carregando={salvando} onPress={salvar} />{editando ? <Botao titulo="Cancelar edição" variante="secundario" onPress={limpar} /> : null}</Cartao>{carregando ? <EstadoTela mensagem="Carregando tipos…" carregando /> : null}{!carregando && tipos.length === 0 ? <EstadoTela mensagem="Nenhum tipo de capim cadastrado." /> : null}{tipos.map((tipo) => <Cartao key={tipo.id} style={estilos.item}><View style={estilos.info}><Text style={estilos.nome}>{tipo.nome}</Text><Text style={estilos.faixa}>{tipo.alturaMinimaCm}–{tipo.alturaMaximaCm} cm</Text></View><View style={estilos.botoes}><Botao titulo="Editar" variante="secundario" onPress={() => editar(tipo)} /><Botao titulo="Excluir" variante="perigo" onPress={() => excluir(tipo)} /></View></Cartao>)}</Tela>;
}
const estilos = StyleSheet.create({ formulario: { gap: espaco.lg }, titulo: { ...tipografia.subheading, color: cores.tinta }, item: { gap: espaco.lg }, info: { gap: espaco.xs }, nome: { ...tipografia.subheading, color: cores.tinta }, faixa: { ...tipografia.body, color: cores.cinzaMedio }, botoes: { gap: espaco.sm } });
